### ISSUE TITLE
Inconsistencies with INTEL extensions

### ISSUE THREAD

**Issue by baldurk** [KhronosGroup/SPIRV-Registry#158]
I found a couple of inconsistencies in the registry with INTEL extensions:

* The `ArbitraryPrecisionIntegersINTEL` capability says it's enabled by `SPV_INTEL_arbitrary_precision_integers`, and that's the name on the [extension page](http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/INTEL/SPV_INTEL_arbitrary_precision_int.html) but the index name and file name is just `SPV_INTEL_arbitrary_precision_int`.
* `RuntimeAlignedAttributeINTEL` from `SPV_INTEL_runtime_aligned` is not listed in the grammar json at all.

On a related but tangential note I've found that quite a few INTEL extensions aren't listed in the registry index nor have specifications, but are referenced in the json. I'm not sure if that's deliberate, if these are intended to be private extensions? As far as I can see enumerants are already reserved for vendors via spir-v.xml so it's odd to have otherwise private extensions mentioned in the grammar.

**Comment by mkinsner** [comment]
Thanks for calling these out.  I believe that the first should be corrected with https://github.com/KhronosGroup/SPIRV-Registry/pull/173

**Comment by MrSidims** [comment]
Some upstream work to the grammar file: https://github.com/KhronosGroup/SPIRV-Headers/pull/298 ; more to go

**Comment by bashbaug** [comment]
Both of the specific inconsistencies identified in this issue are fixed now:
* The name of the arbitrary precision integers extension was fixed by #173.
* RuntimeAlignedAttributeINTEL was added to the grammar file by #298.

If there are no other specific issues to address I think we should close this issue.

Regarding the meta comment that not all of our extensions are published on the registry, this is something we're working to fix.  If there are specific extensions that are listed in the grammar file but not on the registry that are causing problems (or, that sound interesting!), please let us know and we'll try to prioritize those first - thanks!
