### ISSUE TITLE
SPV_KHR_cooperative_matrix initial specification clarifications

### ISSUE THREAD

**Issue by kpet** [KhronosGroup/SPIRV-Registry#208]
We recently merged the first public revision of the SPV_KHR_cooperative_matrix specification. I'm creating this issue to record/bundle clarification requests and proposals for an upcoming revision of the specification.

1. The language we use to describe the _Memory Operand_ operand to **OpCooperativeMatrixLoadKHR** and **OpCooperativeMatrixStoreKHR** does not make it clear that multiple words can be used. We should align the language to that used for **OpLoad**, **OpStore**, etc.
2. What are the type constraints for the _Pointer_ operand to **OpCooperativeMatrixLoadKHR** and **OpCooperativeMatrixStoreKHR**? Specifically, does the pointee type need to be a scalar or vector *of the same type as the matrix's component type* or can it be any scalar or vector type.
PROPOSED RESOLUTION: Constrain the pointee type to be a scalar or vector of the same type as the matrix's component type.
RESOLUTION: Type mismatches were intended and are helpful to efficiently load into shared memory. The Vulkan spec provides alignment guarantees. No change.

**Comment by alan-baker** [comment]
The new instructions (matmul, load, and store) require uniform control flow within the scope of the operation, but that restriction was not added for the existing operations that now support cooperative matrices (e.g. conversions and arithmetic). Perhaps the restriction should be moved to the type and exception be made for matrix length. Something like:
> All dynamic instances of an instruction with an operand that is an object of this type must be executed such that all the invocations in the _Scope_ instance are active or none of them are.

The requirement uniform values can stay in load and store. Object excludes OpCooperativeMatrixLengthKHR since the operand is a type.

**Comment by alan-baker** [comment]
Similar questions about value uniformity. Which values are actually required to be dynamically uniform? Only load/store parameters are currently called out. Examples:
* Must the single constituent for OpCompositeConstruct by dynamically uniform? (This is a requirement of Fill in HLSL WaveMatrix)
* What about OpMatrixTimesScalar?
* Can cooperative matrices be the result of OpSelect or OpPhi (uniform or non-uniform selectors)?

**Comment by jeffbolznv** [comment]
We discussed this briefly in the group today. One case where we want to allow some nonuniform control flow is if a matrix has a different length on different threads, then we at least would want to allow component access to work in nonuniform control flow because a loop over the components would be nonuniform.

IMO the spec should only forbid cases that we think actually lead to undefined behavior, and things that may just cause implementation-dependent values can still be considered valid SPIR-V.

Whatever we decide, I agree we should clarify it in the spec.

**Comment by bashbaug** [comment]
Minor: The cooperative matrix spec doesn't list **CooperativeMatrixKHR** as an enabling capability for any of the cooperative matrix operands, the cooperative matrix layouts, or the cooperative matrix uses, but I think it should.

Note that all of these new enums _are_ currently gated by **CooperativeMatrixKHR** in the SPIR-V grammar ([link](https://github.com/KhronosGroup/SPIRV-Headers/blob/f1ba373ef03752ee9f6f2b898bea1213f93e1ef2/include/spirv/unified1/spirv.core.grammar.json#L15372)).

**Comment by bashbaug** [comment]
There is also a minor naming inconsistency between the cooperative matrix operands, which do not have a KHR suffix (e.g. **MatrixASignedComponents**), and the cooperative matrix layouts and uses, which do have a KHR suffix (e.g. **RowMajorKHR** and **MatrixAKHR**).
